[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 0.98
blur = true

option_as_alt = "Both"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[colors.primary]
background = '#1b1f32'
foreground = '#9094a7'

[colors.normal]
black = '#1b1f32'
red = '#627af4'
green = '#a6e3a1'
yellow = '#99e9ff'
blue = '#89b4fa'
magenta = '#67c9e4'
cyan = '#8b9efd'
white = '#9094a7'

[colors.bright]
black = '#51587b'
red = '#75d5f0'
green = '#94e2d5'
yellow = '#444b6f'
blue = '#74c7ec'
magenta = '#c3cdfe'
cyan = '#5cbcd6'
white = '#9094a7'

