[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 0.98
blur = true

option_as_alt = "Both"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[colors.primary]
background = '#191724'
foreground = '#E0DEF4'

[colors.normal]
black = '#191724'
red = '#EB6F92'
green = '#9CCFD8'
yellow = '#F6C177'
blue = '#31748F'
magenta = '#C4A7E7'
cyan = '#EBBCBA'
white = '#E0DEF4'

[colors.bright]
black = '#6E6A86'
red = '#EB6F92'
green = '#9CCFD8'
yellow = '#F6C177'
blue = '#31748F'
magenta = '#C4A7E7'
cyan = '#EBBCBA'
white = '#E0DEF4'

