[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.9
blur = true
decorations = "Full"
option_as_alt = "Both"

[font]
size = 14.0

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[colors.primary]
background = "#0f111c"
foreground = "#9094a7"

[colors.normal]
black = "#1b1f32"
red = "#627af4"
green = "#67c9e4"
yellow = "#99e9ff"
blue = "#7289fd"
magenta = "#67c9e4"
cyan = "#8b9efd"
white = "#9094a7"

[colors.bright]
black = "#51587b"
red = "#75d5f0"
green = "#80f2ff" 
yellow = "#bffffa"
blue = "#a6b3ff"
magenta = "#c3cdfe"
cyan = "#5cbcd6"
white = "#ffffff"

